#!/bin/bash
source $(dirname "${0}")/_local-hook-exec
declare scriptDir=$(cd $(dirname $0) || exit;pwd)
declare parentDir="$(dirname "${scriptDir}")"
declare HAS_NOT_NODE;
# if "NO_SECRET" is defined, skip secretlint
if [[ -n "${NO_SECRET}" ]]; then
  exit 0
fi
HAS_NOT_NODE=$(command -v node || echo "not found")
if [[ "${HAS_NOT_NODE}" == "not found" ]]; then
  exit 0
fi
declare FILES
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | sed 's|\[|\\\\[|g' | sed 's|\]|\\\\]|g')
[ -z "$FILES" ] && exit 0

# secretlint
echo "  ▶ Check credentials by secretlint"
if [ -f "$PWD/.secretlintignore" ]; then
    echo "$FILES" | xargs "${parentDir}/node_modules/.bin/secretlint" --secretlintignore "$PWD/.secretlintignore" --secretlintrc "${parentDir}/.secretlintrc.json"
else
    echo "$FILES" | xargs "${parentDir}/node_modules/.bin/secretlint" --secretlintrc "${parentDir}/.secretlintrc.json"
fi

# textlint
echo "  ▶ Check text by textlint"
if [ -f "$PWD/.textlintignore" ]; then
    echo "$FILES" | xargs "${parentDir}/node_modules/.bin/textlint" --ignore-path "$PWD/.textlintignore" --config "${parentDir}/.textlintrc.json"
else
    echo "$FILES" | xargs "${parentDir}/node_modules/.bin/textlint" --config "${parentDir}/.textlintrc.json"
fi

RET=$?
if [ $RET -eq 0 ] ;then
    exit 0
else
    exit 1
fi
